---
title: "README merging-souverainete"
author: "Hubert Cadieux"
format: html
editor: visual
---

## Introduction

Ce document sert de guide technique aux étudiants qui participeront à la fusion de nos différents sondages comportant des questions sur l'indépendance du Québec.

Chaque jeu de données aura son propre **source_id** qui permettra d'identifier le sondage auquel un répondant a participé. Dans chacun de ces sondages, les répondants auront aussi leur propre **resp_id** (respondent id) afin de pouvoir éventuellement accéder à des variables qui n'auront pas été intégrées dans le jeu de données fusionné initial.

Le lien suivant mène au Google Sheets qui servira à suivre le progrès du projet: <https://docs.google.com/spreadsheets/d/1ZE6u7hilcsm_sRMNnTeZ6LSx83gqP4I4LiGKsscnsqk/edit#gid=1898178739>

## Description des sondages

### CES (1965-2021)

**source_id**: ces1965, ces1968, etc.

### Pilote 1 de Datagotchi (2021)

**source_id**: datagotchi_pilot1_2021

### Omnibus (2022)

**source_id**: omnibus, omnibus_january, omnibus_february, etc.

### Pilote 2 de Datagotchi, (2022)

**source_id**: datagotchi_pilot2_2022

### Sondage sur le nationalisme avec Evelyne Brie (2022)

**source_id**: sondage_nationalisme_2022

### PES Élections 2022 (2023)

**source_id**: pes_elxn_2022

### Pilote Projet Quorum-MCQ (2023)

**source_id**: quorum_mcq_pilote

### Sondage conseil privé Yannick (2014?)

**source_id**: pco

## Variables à fusionner

\*Toujours mettre la catégorie de la variable comme préfixe avec un `.` entre les deux: `meta.source_id`, `ses.riding`, `ses.qc_region`, `vote.rci_QS`, etc.

La liste suivante contient les variables "meta" qui permettent d'obtenir des informations par rapport au sondage auquel le répondant a participé.

-   **source_id** (id du sondage)
-   **source_resp_id** (id du répondant à l'intérieur du sondage)
    -   probablement simplement un chiffre de 1 à `nrow(data)`
-   **respondent_id** (id unique du répondant à travers notre jeu de données fusionné)
    -   concaténation de **source_id** et **source_resp_id**. Cet id permet d'identifier le répondant de façon unique quand on va tout fusionner.
-   **year** (année du sondage)
-   **month** (mois du sondage)
-   **country** (pays du sondage)
    -   un peu inutile puisque ce sera simplement `qc`

La liste suivante contient les variables qui seront intégrées dans le jeu de données final lorsque présentes dans les différents sondages. Lorsqu'un jeu de données ne contient pas une variable dans cette liste, la colonne sera remplie de `NA` pour ce jeu de données. Il est important d'uniformiser le nom des variables dans les différents fichiers de nettoyage afin d'assurer la cohérence du jeu de données fusionné.

-   Pays d'origine

Il est important de parcourir le codebook du jeu de données brut afin d'être sûr de ne pas oublier de variables.

## Écrire le codebook

Dans le Google Sheets à la feuille `recherche-souverainete_codebook`, vous pouvez noter comment vous codez la variable. Vous pouvez la noter dans un format liste comme suit:

```         
{
"class": "numeric",
"question_label": "Quelle est votre position sur le statut politique du Québec?",
"choices": [
        {
        "value": 0,
        "label": "Fortement en faveur que le Québec reste à l'intérieur du Canada"
      },
        {
        "value": 0.33,
        "label": "Modérément en faveur que le Québec reste à l'intérieur du Canada"
      },
      {
        "value": 0.67,
        "label": "Modérément en faveur que le Québec devienne un pays"
      },
      {
        "value": 1,
        "label": "Fortement en faveur que le Québec devienne un pays"
      }
]
}
```

### Comment coder les variables?

La section suivante contient la marche à suivre pour nettoyer les différentes variables. Il est préférable de perdre un peu d'information dans une variable (par exemple en groupant certaines catégories ensemble) afin qu'elle puisse fusionner avec les variables d'autres jeux de données.

Si une variable ne peut pas être nettoyée de la même façon que présentée dans cette section, une option peut être de créer une variable alternative qui contient le nom uniformisé de la variable ainsi que le **source_id** du jeu de données. N'hésitez pas à poser des questions au reste de l'équipe pour que le jeu de données soit cohérent.

## PROCÉDURE DE BASE

1.  Fouiller dans le codebook du sondage.

-   La première étape sera de fouiller attentivement le codebook du sondage qui vous est assigné pour être surs de trouver toutes les variables qui nous intéressent.

2.  Créer le fichier de cleaning *des variables qui nous intéressent* de votre sondage au bon endroit.
3.  ***SI VOUS NETTOYEZ UNE VARIABLE QUI A DÉJÀ ÉTÉ NETTOYÉE***: fiez-vous le plus possible à ce qui a déjà été fait pour reproduire les bonnes catégories
4.  ***SI VOUS NETTOYEZ UNE VARIABLE QUI N'A PAS ENCORE ÉTÉ NETTOYÉE***: allez voir dans **les autres codebooks** comment la nettoyer de façon à être bien fusionnée avec les autres (plus petit dénominateur commun). S'il est impossible de nettoyer
